/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_museui_component_NativeWindow */

#ifndef _Included_com_museui_component_NativeWindow
#define _Included_com_museui_component_NativeWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_museui_component_NativeWindow
 * Method:    createWindow
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_museui_component_NativeWindow_createWindow
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_museui_component_NativeWindow
 * Method:    messageLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_museui_component_NativeWindow_messageLoop
  (JNIEnv *, jobject);

/*
 * Class:     com_museui_component_NativeWindow
 * Method:    blitFrameBuffer
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_com_museui_component_NativeWindow_blitFrameBuffer
  (JNIEnv *, jobject, jlong, jintArray, jint, jint);

/*
 * Class:     com_museui_component_NativeWindow
 * Method:    registerInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_museui_component_NativeWindow_registerInstance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
